#Global messages configuration section
entry_message: 'Hi %player% have fun!' #Change message to what you like or leave it '' to disable message
welcome_broadcast: '%player% joined our server!' #Change message to what you like or leave it '' to disable message
welcome_admin: 'Administrator %admin% joined server' #Change message to what you like or leave it '' to disable message
no_permission: '&cYou do not have permission to use this command'
#Admin panel configuration section
admin_login: 'Welcome %admin% on server :)' #Change message to what you like or leave it '' to disable message
admin_permission: 'vanilla.admin' # Default permission for admin
admin_panel_header: '&f[&c+&f]&f Vertuli Panel &f[&c+&f]' # Text on chat when admin is logged into the panel
admin_announce: 'enable' # enable/disable to announce admin panel log in/out to players
admin_announce_msg_login: "&fAdmin &e%admin% &fhas logged &cin &finto panel!"
admin_announce_msg_logout: "&fAdmin &e%admin% &fhas logged &cout &ffrom panel!"
admin_panel: 'enable' # enable/disable to turn on/off admin panel after logon
#Chat moderation configuration section
admin_chat_permission: 'vanilla.chat'
chat_enable_message: '&f[&c+&f]&f Chat has been &aenabled'
chat_disable_message: '&f[&c+&f]&f Chat has been &cdisabled'
chat_clear_message: '&f[&c+&f]&f Chat has been &acleared'
chat_disabled_message: '&f[&c+&f]&f Chat is currently &cdisabled'